### ISSUE TITLE
Unexpected behaviour when using mpl_style with plt.savefig()

### ISSUE THREAD

**Issue by PsiPhiTheta** [quantumblacklabs/qbstyles#8] opened 2019-08-12 10:25 UTC
Consider the following minimal working example which demonstrates unexpected behaviour when using `qbstyles.mpl_style` with `plt.savefig()`:

```
import matplotlib.pyplot as plt
from qbstyles import mpl_style
mpl_style(dark=True)
a = [1,2,3,4,5]
plt.plot(a)
plt.savefig('filename.png')
```

The output image is missing most elements and does not have the qbstyle applied:
![filename](https://user-images.githubusercontent.com/25353324/62858916-9d153b80-bcf3-11e9-9b62-908a89f0cb8a.png)

**Comment by tsanikgr** [comment] 2019-08-27 09:58
Hello @PsiPhiTheta.

Are you trying to plot in a Jupyter notebook?
Have you read [this](https://github.com/quantumblacklabs/qbstyles#how-do-i-use-qb-styles-in-jupyter-notebooks) warning on our README?

I cannot reproduce your issue otherwise, any further info would be much appreciated. Thanks!

**Comment by PsiPhiTheta** [comment] 2019-08-27 10:31
Hi @tsanikgr,

Thanks for your help. Actually I am not using Jupyter, I am using Python v3.7, matplotlib v3.1.1, qbstyles v0.1.2 via the PyCharm IDE v2019.2.1 for macOS.

Happy to provide any further info as needed.

**Comment by tsanikgr** [comment] 2019-08-28 10:51
Hello @PsiPhiTheta,

Thanks for spotting this bug! `plt.show()` works, but as you correctly identified `plt.savefig()` was not applying the `facecolor`. In the `dark` theme, this defaulted to white so you could not see anything.

I just merged #9 which fixes this bug (and another one).

We will release to `pypi` in a couple of hours, after which you 'll be able to update using `pip install qbstyles -U`.

In the meantime, if you would like to try the fix you can clone the repo and do `pip install . -U`

Thanks again!

**Comment by PsiPhiTheta** [comment] 2019-08-28 11:05
Thanks @tsanikgr, I'll test this fix tomorrow and will report the results back here.

**Comment by tsanikgr** [comment] 2019-08-28 12:36
We released and it works on my machine. Just update with `pip install qbstyles -U`

Thanks again for reporting :)

---
Fixed by #9

**Closed by tsanikgr** 2019-08-28 12:36 UTC

**Comment by PsiPhiTheta** [comment] 2019-08-28 13:03
Also working on my end, cheers @tsanikgr.
